version = 0.1

[default.deploy.parameters]
stack_name = "jobot-ai"
resolve_s3 = true
s3_prefix = "jobot-ai"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "sa-east-1"
